import { Patient } from './types';

export const mockPatients: Patient[] = [
  {
    id: 1,
    name: 'Joshua White',
    email: 'joshuaWK@gmail.com',
    gender: 'Male',
    age: '59yo',
    diagnosis: 'Prostate',
    status: 'Urgent',
    blood: '0+',
    lastVisit: '12-05-2025',
    contactNumber: '(201) 555-0124',
    dateOfBirth: '1 Jan, 1985',
    memberSince: '3 March, 2023',
    address: 'St Louis, NY',
    class: 'Class',
    diagnosisCode: 'ICD34',
    stage: 'IIA',
    erStatus: 'Positive',
    reports: {
      drugPrescription: true,
      clinicalData: true,
      suggestedTreatment: true,
    },
  },
  {
    id: 2,
    name: 'Joshua White',
    email: 'joshuaWK@gmail.com',
    gender: 'Male',
    age: '59yo',
    diagnosis: 'Prostate',
    status: 'Emergency',
    blood: '0+',
    lastVisit: '12-05-2025',
    contactNumber: '(201) 555-0124',
    dateOfBirth: '1 Jan, 1985',
    memberSince: '3 March, 2023',
    address: 'St Louis, NY',
    class: 'Class',
    diagnosisCode: 'ICD34',
    stage: 'IIA',
    erStatus: 'Positive',
    reports: {
      drugPrescription: false,
      clinicalData: false,
      suggestedTreatment: false,
    },
  },
  {
    id: 3,
    name: 'Joshua White',
    email: 'joshuaWK@gmail.com',
    gender: 'Male',
    age: '59yo',
    diagnosis: 'Prostate',
    status: 'Past Patient',
    blood: '0+',
    lastVisit: '12-05-2025',
    contactNumber: '(201) 555-0124',
    dateOfBirth: '1 Jan, 1985',
    memberSince: '3 March, 2023',
    address: 'St Louis, NY',
    class: 'Class',
    diagnosisCode: 'ICD34',
    stage: 'IIA',
    erStatus: 'Positive',
    reports: {
      drugPrescription: false,
      clinicalData: false,
      suggestedTreatment: false,
    },
  },
  {
    id: 4,
    name: 'Joshua White',
    email: 'joshuaWK@gmail.com',
    gender: 'Male',
    age: '59yo',
    diagnosis: 'Prostate',
    status: 'Treated',
    blood: '0+',
    lastVisit: '12-05-2025',
    contactNumber: '(201) 555-0124',
    dateOfBirth: '1 Jan, 1985',
    memberSince: '3 March, 2023',
    address: 'St Louis, NY',
    class: 'Class',
    diagnosisCode: 'ICD34',
    stage: 'IIA',
    erStatus: 'Positive',
    reports: {
      drugPrescription: true,
      clinicalData: true,
      suggestedTreatment: true,
    },
  },
  {
    id: 5,
    name: 'Joshua White',
    email: 'joshuaWK@gmail.com',
    gender: 'Male',
    age: '59yo',
    diagnosis: 'Prostate',
    status: 'Urgent',
    blood: '0+',
    lastVisit: '12-05-2025',
    contactNumber: '(201) 555-0124',
    dateOfBirth: '1 Jan, 1985',
    memberSince: '3 March, 2023',
    address: 'St Louis, NY',
    class: 'Class',
    diagnosisCode: 'ICD34',
    stage: 'IIA',
    erStatus: 'Positive',
    reports: {
      drugPrescription: false,
      clinicalData: false,
      suggestedTreatment: false,
    },
  },
  {
    id: 6,
    name: 'Joshua White',
    email: 'joshuaWK@gmail.com',
    gender: 'Male',
    age: '59yo',
    diagnosis: 'Prostate',
    status: 'Treated',
    blood: '0+',
    lastVisit: '12-05-2025',
    contactNumber: '(201) 555-0124',
    dateOfBirth: '1 Jan, 1985',
    memberSince: '3 March, 2023',
    address: 'St Louis, NY',
    class: 'Class',
    diagnosisCode: 'ICD34',
    stage: 'IIA',
    erStatus: 'Positive',
    reports: {
      drugPrescription: false,
      clinicalData: false,
      suggestedTreatment: false,
    },
  },
  {
    id: 7,
    name: 'Joshua White',
    email: 'joshuaWK@gmail.com',
    gender: 'Male',
    age: '59yo',
    diagnosis: 'Prostate',
    status: 'Past Patient',
    blood: '0+',
    lastVisit: '12-05-2025',
    contactNumber: '(201) 555-0124',
    dateOfBirth: '1 Jan, 1985',
    memberSince: '3 March, 2023',
    address: 'St Louis, NY',
    class: 'Class',
    diagnosisCode: 'ICD34',
    stage: 'IIA',
    erStatus: 'Positive',
    reports: {
      drugPrescription: false,
      clinicalData: false,
      suggestedTreatment: false,
    },
  },
  {
    id: 8,
    name: 'Joshua White',
    email: 'joshuaWK@gmail.com',
    gender: 'Male',
    age: '59yo',
    diagnosis: 'Prostate',
    status: 'Urgent',
    blood: '0+',
    lastVisit: '12-05-2025',
    contactNumber: '(201) 555-0124',
    dateOfBirth: '1 Jan, 1985',
    memberSince: '3 March, 2023',
    address: 'St Louis, NY',
    class: 'Class',
    diagnosisCode: 'ICD34',
    stage: 'IIA',
    erStatus: 'Positive',
    reports: {
      drugPrescription: false,
      clinicalData: false,
      suggestedTreatment: false,
    },
  },
];
