import { CaseActivity, Doctor, CountryRate, ChartData } from './type';

export const caseActivities: CaseActivity[] = [
  {
    id: '1',
    patient: 'Sarah Johnson',
    caseNumber: '#1234',
    cancerType: 'Breast',
    stage: 'IIA',
    age: '54',
    date: '21/09/2025',
  },
  {
    id: '2',
    patient: 'Michael Chen',
    caseNumber: '#1235',
    cancerType: 'Cervical',
    stage: 'IB',
    age: '47',
    date: '20/09/2025',
  },
  {
    id: '3',
    patient: 'Robert Williams',
    caseNumber: '#1236',
    cancerType: 'Prostate',
    stage: 'IIIA',
    age: '62',
    date: '19/09/2025',
  },
  {
    id: '4',
    patient: 'Emily Davis',
    caseNumber: '#1237',
    cancerType: 'Lung',
    stage: 'IIA',
    age: '58',
    date: '18/09/2025',
  },
  {
    id: '5',
    patient: 'James Martinez',
    caseNumber: '#1238',
    cancerType: 'Colorectal',
    stage: 'IIB',
    age: '51',
    date: '17/09/2025',
  },
  {
    id: '6',
    patient: 'Lisa Anderson',
    caseNumber: '#1239',
    cancerType: 'Ovarian',
    stage: 'IC',
    age: '45',
    date: '16/09/2025',
  },
  {
    id: '7',
    patient: 'David Thompson',
    caseNumber: '#1240',
    cancerType: 'Melanoma',
    stage: 'IIA',
    age: '39',
    date: '15/09/2025',
  },
  {
    id: '8',
    patient: 'Maria Garcia',
    caseNumber: '#1241',
    cancerType: 'Thyroid',
    stage: 'I',
    age: '43',
    date: '14/09/2025',
  },
  {
    id: '9',
    patient: 'John Wilson',
    caseNumber: '#1242',
    cancerType: 'Pancreatic',
    stage: 'IIA',
    age: '67',
    date: '13/09/2025',
  },
];

export const doctors: Doctor[] = [
  { id: 1, name: 'Dr. Sarah Mitchell', specialty: 'Medical Oncologist', status: 'Available' },
  { id: 2, name: 'Dr. James Patterson', specialty: 'Radiation Oncologist', status: 'Available' },
  { id: 3, name: 'Dr. Emily Rodriguez', specialty: 'Surgical Oncologist', status: 'Available' },
  { id: 4, name: 'Dr. Michael Chang', specialty: 'Hematologist', status: 'Absent' },
  { id: 5, name: 'Dr. Rachel Foster', specialty: 'Gynecologic Oncologist', status: 'Absent' },
  { id: 6, name: 'Dr. David Lee', specialty: 'Thoracic Surgeon', status: 'Absent' },
  { id: 7, name: 'Dr. Amanda Brooks', specialty: 'Pediatric Oncologist', status: 'Available' },
];

export const allCountryRates: CountryRate[] = [
  { country: 'United States', countryCode: 'us', rate: 75, trend: 28.4 },
  { country: 'Pakistan', countryCode: 'pk', rate: 65, trend: -18.2 },
  { country: 'India', countryCode: 'in', rate: 85, trend: 23.8 },
  { country: 'Brazil', countryCode: 'br', rate: 70, trend: 25.8 },
  { country: 'Nigeria', countryCode: 'ng', rate: 45, trend: 11.9 },
  { country: 'United Kingdom', countryCode: 'gb', rate: 68, trend: 15.3 },
  { country: 'China', countryCode: 'cn', rate: 78, trend: 19.7 },
  { country: 'Japan', countryCode: 'jp', rate: 72, trend: -8.4 },
  { country: 'Germany', countryCode: 'de', rate: 81, trend: 22.1 },
  { country: 'Canada', countryCode: 'ca', rate: 77, trend: 18.9 },
  { country: 'Australia', countryCode: 'au', rate: 69, trend: 12.6 },
  { country: 'South Africa', countryCode: 'za', rate: 52, trend: -5.2 },
  { country: 'France', countryCode: 'fr', rate: 74, trend: 16.8 },
  { country: 'Mexico', countryCode: 'mx', rate: 58, trend: 9.3 },
  { country: 'South Korea', countryCode: 'kr', rate: 80, trend: 21.4 },
];

export const chartData: ChartData[] = [
  { month: 'Jan', value: 245000, x: 80, y: 120 },
  { month: 'Feb', value: 198000, x: 160, y: 140 },
  { month: 'Mar', value: 267000, x: 240, y: 105 },
  { month: 'Apr', value: 225000, x: 320, y: 125 },
  { month: 'May', value: 289000, x: 400, y: 90 },
  { month: 'Jun', value: 302000, x: 480, y: 78 },
  { month: 'Jul', value: 324000, x: 560, y: 60 },
];
