export const mockCases = [
  {
    id: '1',
    patient: 'Joshua White',
    caseNumber: '#1234',
    cancerType: 'Breast',
    stage: 'IIA',
    age: 54,
    date: '21/06/2025',
  },
  {
    id: '2',
    patient: 'Joshua White',
    caseNumber: '#1234',
    cancerType: 'Breast',
    stage: 'IIA',
    age: 54,
    date: '21/06/2025',
  },
  {
    id: '3',
    patient: 'Joshua White',
    caseNumber: '#1234',
    cancerType: 'Breast',
    stage: 'IIA',
    age: 54,
    date: '21/06/2025',
  },
  {
    id: '4',
    patient: 'Joshua White',
    caseNumber: '#0e101144',
    cancerType: 'Breast',
    stage: 'IIA',
    age: 54,
    date: '21/06/2025',
  },
  {
    id: '5',
    patient: 'Joshua White',
    caseNumber: '#1234',
    cancerType: 'Breast',
    stage: 'IIA',
    age: 54,
    date: '21/06/2025',
  },
  {
    id: '6',
    patient: 'Joshua White',
    caseNumber: '#1234',
    cancerType: 'Breast',
    stage: 'IIA',
    age: 54,
    date: '21/06/2025',
  },
  {
    id: '7',
    patient: 'Joshua White',
    caseNumber: '#1234',
    cancerType: 'Breast',
    stage: 'IIA',
    age: 54,
    date: '21/06/2025',
  },
];
